### ISSUE TITLE
Test `same.dataset` functionality, including IPFS, and document on website.

### ISSUE THREAD

**Issue by Bubblyworld** [SAME-Project/same-project#150]

**Comment by Bubblyworld** [comment]
```
E         Traceback (most recent call last):
E           File "/tmp/tmp.ClICOgrRSi", line 143, in <module>
E             _outputs = same_step_000_8a97fcbc0b5f4fb8ad0998ace9074930_fn(**_parsed_args)
E           File "/tmp/tmp.ClICOgrRSi", line 121, in same_step_000_8a97fcbc0b5f4fb8ad0998ace9074930_fn
E             exec(user_code, globals(), globals())
E           File "<string>", line 339, in <module>
E           File "/usr/local/lib/python3.10/site-packages/sameproject/sdk/dataset.py", line 30, in dataset
E             reader = _get_pandas_reader_for(url)
E           File "/usr/local/lib/python3.10/site-packages/sameproject/sdk/dataset.py", line 60, in _get_pandas_reader_for
E             return getattr(pd, extensions[extension])
E         KeyError: ''
```

The `dataset(...)` function doesn't seem to like being given files with no suffix... but we should probably support this in some way.

**Comment by Bubblyworld** [comment]
Other things that need to be fixed:
- we need to inject `same.yaml` and `SAME_ENV` into each step's container since the `sdk` needs the context
- we need to actually use the `SAME_ENV` when deciding which docker image to user
